name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
  

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker compose build

    # TODO update when frontend has unit tests
    # - name: Run Unit Tests
    #   run: docker compose run frontend npm test

    - name: Make Test Request
      run: |
        docker compose up -d
        sleep 5
        curl localhost:4173
        docker compose down

    - name: Trigger Main Workflow
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/repository-dispatch@v2
      with:
        repository: com3014-group9/com3014_meowstagram
        token: ${{ secrets.PAT }}
        event-type: trigger-build